SELECT * from ACCOUNT_STG LIMIT 10;
SELECT * from CASHTRANSACTION_STG LIMIT 10;
SELECT * from CUSTOMER_MGMT_STG LIMIT 10;
-- Customer is empty
SELECT * from CUSTOMER_STG LIMIT 10;
SELECT * from DAILYMARKET_STG LIMIT 10;
SELECT * FROM DATE_STG LIMIT 10;
SELECT * from FINWIRE_STG LIMIT 10;
SELECT * from HOLDINGHISTORY_STG LIMIT 10;
SELECT * from HR_STG LIMIT 10;
SELECT * from INDUSTRY_STG LIMIT 10;
SELECT * from PROSPECT_STG LIMIT 10;
SELECT * from STATUSTYPE_STG LIMIT 10;
SELECT * from TAXRATE_STG LIMIT 10;
SELECT * from TIME_STG LIMIT 10;
SELECT * from TRADEHISTORY_STG LIMIT 10;
-- Trade is empty
SELECT * from TRADE_STG LIMIT 10;  
SELECT * from WATCH_HISTORY_STG LIMIT 10;



