SELECT * from ACCOUNT_STG LIMIT 10;
SELECT * from CASHTRANSACTION_STG LIMIT 10;
SELECT * from CUSTOMER_MGMT_STG LIMIT 10;
-- Customer is empty
SELECT * from CUSTOMER_STG LIMIT 10;
SELECT * from DAILYMARKET_STG LIMIT 10;
SELECT * FROM DATE_STG LIMIT 10;
SELECT * from FINWIRE_STG LIMIT 10;
SELECT * from HOLDINGHISTORY_STG LIMIT 10;
SELECT * from HR_STG LIMIT 10;
SELECT * from INDUSTRY_STG LIMIT 10;
SELECT * from PROSPECT_STG LIMIT 10;
SELECT * from STATUSTYPE_STG LIMIT 10;
SELECT * from TAXRATE_STG LIMIT 10;
SELECT * from TIME_STG LIMIT 10;
SELECT * from TRADEHISTORY_STG LIMIT 10;
-- Trade is empty
SELECT * from TRADE_STG LIMIT 10;  
SELECT * from WATCH_HISTORY_STG LIMIT 10;




-- Truncate all tables
TRUNCATE TABLE ACCOUNT_STG;
TRUNCATE TABLE CASHTRANSACTION_STG;
TRUNCATE TABLE CUSTOMER_MGMT_STG;
TRUNCATE TABLE CUSTOMER_STG;
TRUNCATE TABLE DAILYMARKET_STG;
TRUNCATE TABLE DATE_STG;
TRUNCATE TABLE FINWIRE_STG;
TRUNCATE TABLE HOLDINGHISTORY_STG;
TRUNCATE TABLE HR_STG;
TRUNCATE TABLE INDUSTRY_STG;
TRUNCATE TABLE PROSPECT_STG;
TRUNCATE TABLE STATUSTYPE_STG;
TRUNCATE TABLE TAXRATE_STG;
TRUNCATE TABLE TIME_STG;
TRUNCATE TABLE TRADEHISTORY_STG;
TRUNCATE TABLE TRADE_STG;
TRUNCATE TABLE WATCH_HISTORY_STG;




CALL TPCDI_STG.PUBLIC.START_LOAD_HISTORICAL_TASKS_SP(10);
